version: '3.8'

services:
  portfolio:
    build: .
    container_name: jeneel-portfolio
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    volumes:
      # Optional: Mount for development (uncomment for live reload)
      # - .:/usr/share/nginx/html
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - portfolio-network

  # Optional: Add a reverse proxy with SSL support
  # nginx-proxy:
  #   image: nginxproxy/nginx-proxy
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - certs:/etc/nginx/certs
  #     - vhost:/etc/nginx/vhost.d
  #     - html:/usr/share/nginx/html
  #   restart: unless-stopped
  #   networks:
  #     - portfolio-network

networks:
  portfolio-network:
    driver: bridge

# volumes:
#   certs:
#   vhost:
#   html:
